const express = require('express');
const cookieParser = require('cookie-parser');
const multer = require('multer');
const crypto = require('crypto');
const path = require('path');
const fs = require('fs');
const db = require('./db');

const app = express();
const port = process.env.PORT || 4311;
const uploadDir = path.join(__dirname, '..', 'public', 'uploads');
fs.mkdirSync(uploadDir, { recursive: true });
const upload = multer({ dest: uploadDir, limits: { fileSize: 50 * 1024 * 1024 } });
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(cookieParser());
app.use('/uploads', express.static(uploadDir));
app.use('/vendor/three', express.static(path.join(__dirname, '..', 'node_modules', 'three')));

const publicUser = u => u && ({ id:u.id, phone:u.phone, nickname:u.nickname, role:u.role, isAdmin:!!u.is_admin, bio:u.bio, avatarColor:u.avatar_color });
function auth(req,res,next){
  const token=req.cookies.pl_session; if(!token) return res.status(401).json({error:'请先登录'});
  const u=db.prepare('SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires_at>?').get(token,Date.now());
  if(!u) return res.status(401).json({error:'登录已过期'}); req.user=u; next();
}
function admin(req,res,next){ if(!req.user?.is_admin) return res.status(403).json({error:'需要管理员权限'}); next(); }
function event(orderId,actorId,type,detail=''){db.prepare('INSERT INTO order_events(order_id,actor_id,type,detail) VALUES(?,?,?,?)').run(orderId,actorId,type,detail)}

app.post('/api/auth/code',(req,res)=>{ const phone=String(req.body.phone||''); if(!/^1\d{10}$/.test(phone)) return res.status(400).json({error:'请输入有效手机号'}); const code=phone==='13800000000'?'000000':String(Math.floor(100000+Math.random()*900000)); db.prepare('INSERT OR REPLACE INTO otp_codes VALUES(?,?,?)').run(phone,code,Date.now()+300000); res.json({ok:true,devCode:code,message:'验证码已发送（开发环境直接回显）'}); });
app.post('/api/auth/login',(req,res)=>{ const {phone,code,nickname}=req.body; const row=db.prepare('SELECT * FROM otp_codes WHERE phone=? AND code=? AND expires_at>?').get(phone,code,Date.now()); if(!row) return res.status(400).json({error:'验证码错误或已过期'}); let u=db.prepare('SELECT * FROM users WHERE phone=?').get(phone); if(!u){ const info=db.prepare('INSERT INTO users(phone,nickname) VALUES(?,?)').run(phone,nickname||`用户${phone.slice(-4)}`); u=db.prepare('SELECT * FROM users WHERE id=?').get(info.lastInsertRowid); } const token=crypto.randomBytes(24).toString('hex'); db.prepare('INSERT INTO sessions VALUES(?,?,?)').run(token,u.id,Date.now()+30*86400000); res.cookie('pl_session',token,{httpOnly:true,sameSite:'lax',maxAge:30*86400000}); res.json({user:publicUser(u)}); });
app.post('/api/auth/logout',auth,(req,res)=>{db.prepare('DELETE FROM sessions WHERE token=?').run(req.cookies.pl_session);res.clearCookie('pl_session');res.json({ok:true})});
app.get('/api/me',(req,res)=>{ const token=req.cookies.pl_session; const u=token&&db.prepare('SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token=? AND s.expires_at>?').get(token,Date.now()); res.json({user:publicUser(u)}); });

app.get('/api/config',(req,res)=>res.json({materials:db.prepare('SELECT * FROM materials WHERE active=1 ORDER BY sort_order').all(),colors:db.prepare('SELECT * FROM color_options WHERE active=1 ORDER BY id').all(),rules:Object.fromEntries(db.prepare('SELECT * FROM pricing_rules').all().map(x=>[x.key,x]))}));
app.get('/api/demands',(req,res)=>{ const where=req.query.mine&&req.query.mine!=='false'?'WHERE d.user_id=?':"WHERE d.status IN ('open','quoted')"; const args=where.includes('?')?[Number(req.query.mine)]:[]; const rows=db.prepare(`SELECT d.*,u.nickname,(SELECT COUNT(*) FROM quotes q WHERE q.demand_id=d.id) quote_count FROM demands d JOIN users u ON u.id=d.user_id ${where} ORDER BY d.created_at DESC`).all(...args); res.json(rows); });
app.get('/api/demands/:id',(req,res)=>{const d=db.prepare('SELECT d.*,u.nickname FROM demands d JOIN users u ON u.id=d.user_id WHERE d.id=?').get(req.params.id);if(!d)return res.status(404).json({error:'需求不存在'});const quotes=db.prepare('SELECT q.*,u.nickname,p.name printer_name,p.model printer_model,p.max_x,p.max_y,p.max_z,p.color_mode FROM quotes q JOIN users u ON u.id=q.user_id JOIN printers p ON p.id=q.printer_id WHERE q.demand_id=? ORDER BY q.amount').all(req.params.id);res.json({...d,quotes})});
app.post('/api/demands',auth,upload.single('model'),(req,res)=>{const b=req.body; if(!b.title||!b.description||!b.material_code||!b.color_name) return res.status(400).json({error:'请填写完整需求'}); const info=db.prepare(`INSERT INTO demands(user_id,title,description,material_code,color_name,quantity,size_x,size_y,size_z,estimated_weight,estimated_hours,budget,deadline,delivery_method,city,model_file,model_name,authorized_public) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(req.user.id,b.title,b.description,b.material_code,b.color_name,+b.quantity||1,+b.size_x||0,+b.size_y||0,+b.size_z||0,+b.estimated_weight||0,+b.estimated_hours||0,+b.budget||0,b.deadline||'',b.delivery_method||'express',b.city||'',req.file?`/uploads/${req.file.filename}`:'',req.file?.originalname||'',b.authorized_public==='true'?1:0); res.json({id:info.lastInsertRowid,status:'pending_review'}); });
app.post('/api/demands/:id/review',auth,admin,(req,res)=>{const status=req.body.action==='approve'?'open':'rejected';db.prepare('UPDATE demands SET status=?,reject_reason=? WHERE id=?').run(status,req.body.reason||'',req.params.id);res.json({ok:true,status})});
app.get('/api/admin/reviews',auth,admin,(req,res)=>res.json(db.prepare("SELECT d.*,u.nickname FROM demands d JOIN users u ON u.id=d.user_id WHERE d.status='pending_review' ORDER BY d.created_at").all()));

app.get('/api/printers',auth,(req,res)=>res.json(db.prepare('SELECT * FROM printers WHERE user_id=? ORDER BY id DESC').all(req.user.id).map(x=>({...x,materials:JSON.parse(x.materials)}))));
app.post('/api/printers',auth,(req,res)=>{const b=req.body;const info=db.prepare('INSERT INTO printers(user_id,name,model,technology,max_x,max_y,max_z,color_mode,max_colors,materials,nozzle,enclosed,location,description) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(req.user.id,b.name,b.model,b.technology||'FDM',+b.max_x,+b.max_y,+b.max_z,b.color_mode||'single',+b.max_colors||1,JSON.stringify(b.materials||[]),b.nozzle||'0.4mm',b.enclosed?1:0,b.location||'',b.description||'');db.prepare("UPDATE users SET role='maker' WHERE id=?").run(req.user.id);res.json({id:info.lastInsertRowid})});
app.post('/api/demands/:id/quotes',auth,(req,res)=>{const b=req.body;const d=db.prepare("SELECT * FROM demands WHERE id=? AND status IN ('open','quoted')").get(req.params.id);if(!d)return res.status(400).json({error:'该需求当前不接受报价'});if(d.user_id===req.user.id)return res.status(400).json({error:'不能为自己的需求报价'});const p=db.prepare('SELECT * FROM printers WHERE id=? AND user_id=?').get(b.printer_id,req.user.id);if(!p)return res.status(400).json({error:'请先选择自己的打印机'});try{db.prepare('INSERT INTO quotes(demand_id,printer_id,user_id,amount,days,message) VALUES(?,?,?,?,?,?)').run(req.params.id,p.id,req.user.id,+b.amount,+b.days,b.message);db.prepare("UPDATE demands SET status='quoted' WHERE id=?").run(req.params.id);res.json({ok:true})}catch(e){res.status(400).json({error:'你已经报价过该需求'})}});
app.post('/api/quotes/:id/accept',auth,(req,res)=>{const q=db.prepare('SELECT q.*,d.user_id buyer_id FROM quotes q JOIN demands d ON d.id=q.demand_id WHERE q.id=?').get(req.params.id);if(!q||q.buyer_id!==req.user.id)return res.status(403).json({error:'无权选择此报价'});const no=`PL${Date.now().toString().slice(-10)}`;const tx=db.transaction(()=>{db.prepare("UPDATE quotes SET status=CASE WHEN id=? THEN 'accepted' ELSE 'declined' END WHERE demand_id=?").run(q.id,q.demand_id);db.prepare("UPDATE demands SET status='matched' WHERE id=?").run(q.demand_id);return db.prepare('INSERT INTO orders(order_no,demand_id,quote_id,buyer_id,maker_id,amount) VALUES(?,?,?,?,?,?)').run(no,q.demand_id,q.id,q.buyer_id,q.user_id,q.amount).lastInsertRowid});const id=tx();event(id,req.user.id,'quote_accepted',`选择报价 ¥${q.amount}`);res.json({id,orderNo:no})});

app.get('/api/orders',auth,(req,res)=>res.json(db.prepare(`SELECT o.*,d.title,b.nickname buyer_name,m.nickname maker_name FROM orders o JOIN demands d ON d.id=o.demand_id JOIN users b ON b.id=o.buyer_id JOIN users m ON m.id=o.maker_id WHERE o.buyer_id=? OR o.maker_id=? ORDER BY o.created_at DESC`).all(req.user.id,req.user.id)));
app.get('/api/orders/:id',auth,(req,res)=>{const o=db.prepare(`SELECT o.*,d.title,d.description,d.model_file,d.model_name,d.material_code,d.color_name,d.quantity,b.nickname buyer_name,m.nickname maker_name FROM orders o JOIN demands d ON d.id=o.demand_id JOIN users b ON b.id=o.buyer_id JOIN users m ON m.id=o.maker_id WHERE o.id=? AND (o.buyer_id=? OR o.maker_id=?)`).get(req.params.id,req.user.id,req.user.id);if(!o)return res.status(404).json({error:'订单不存在'});o.events=db.prepare('SELECT e.*,u.nickname FROM order_events e JOIN users u ON u.id=e.actor_id WHERE order_id=? ORDER BY e.id').all(o.id);o.reviews=db.prepare('SELECT r.*,u.nickname FROM reviews r JOIN users u ON u.id=r.from_user_id WHERE order_id=?').all(o.id);res.json(o)});
app.post('/api/orders/:id/action',auth,(req,res)=>{const o=db.prepare('SELECT * FROM orders WHERE id=? AND (buyer_id=? OR maker_id=?)').get(req.params.id,req.user.id,req.user.id);if(!o)return res.status(404).json({error:'订单不存在'});const a=req.body.action;let status=o.status,escrow=o.escrow_status,fields={};if(a==='pay'&&req.user.id===o.buyer_id&&status==='awaiting_payment'){status='paid';escrow='held';fields.paid_at=new Date().toISOString()}else if(a==='start'&&req.user.id===o.maker_id&&status==='paid')status='printing';else if(a==='ship'&&req.user.id===o.maker_id&&status==='printing'){status='shipped';fields.shipped_at=new Date().toISOString();fields.carrier=req.body.carrier||'';fields.tracking_no=req.body.tracking_no||'';fields.proof=req.body.proof||''}else if(a==='complete'&&req.user.id===o.buyer_id&&status==='shipped'){status='completed';escrow='released';fields.completed_at=new Date().toISOString()}else if(a==='dispute'&&['paid','printing','shipped'].includes(status)){status='disputed';fields.dispute_reason=req.body.reason||''}else return res.status(400).json({error:'当前状态不能执行此操作'});db.prepare('UPDATE orders SET status=?,escrow_status=?,paid_at=COALESCE(?,paid_at),shipped_at=COALESCE(?,shipped_at),completed_at=COALESCE(?,completed_at),carrier=COALESCE(?,carrier),tracking_no=COALESCE(?,tracking_no),proof=COALESCE(?,proof),dispute_reason=COALESCE(?,dispute_reason) WHERE id=?').run(status,escrow,fields.paid_at||null,fields.shipped_at||null,fields.completed_at||null,fields.carrier||null,fields.tracking_no||null,fields.proof||null,fields.dispute_reason||null,o.id);event(o.id,req.user.id,a,req.body.reason||req.body.tracking_no||'');res.json({ok:true,status,escrow})});
app.post('/api/orders/:id/review',auth,(req,res)=>{const o=db.prepare('SELECT * FROM orders WHERE id=? AND status=? AND (buyer_id=? OR maker_id=?)').get(req.params.id,'completed',req.user.id,req.user.id);if(!o)return res.status(400).json({error:'订单尚未完成'});const to=req.user.id===o.buyer_id?o.maker_id:o.buyer_id;try{db.prepare('INSERT INTO reviews(order_id,from_user_id,to_user_id,rating,content) VALUES(?,?,?,?,?)').run(o.id,req.user.id,to,Math.max(1,Math.min(5,+req.body.rating)),req.body.content||'');res.json({ok:true})}catch(e){res.status(400).json({error:'你已经评价过此订单'})}});

app.get('/api/admin/config',auth,admin,(req,res)=>res.json({materials:db.prepare('SELECT * FROM materials ORDER BY sort_order').all(),rules:db.prepare('SELECT * FROM pricing_rules').all(),colors:db.prepare('SELECT * FROM color_options ORDER BY id').all()}));
app.put('/api/admin/materials/:id',auth,admin,(req,res)=>{const b=req.body;db.prepare('UPDATE materials SET name=?,price_per_gram=?,market_range=?,active=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(b.name,+b.price_per_gram,b.market_range,b.active?1:0,req.params.id);res.json({ok:true})});
app.put('/api/admin/rules/:key',auth,admin,(req,res)=>{db.prepare('UPDATE pricing_rules SET value=? WHERE key=?').run(+req.body.value,req.params.key);res.json({ok:true})});
app.put('/api/admin/colors/:id',auth,admin,(req,res)=>{const b=req.body;db.prepare('UPDATE color_options SET name=?,hex=?,multiplier=?,active=? WHERE id=?').run(b.name,b.hex,+b.multiplier,b.active?1:0,req.params.id);res.json({ok:true})});

app.use(express.static(path.join(__dirname,'..','public')));
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'..','public','index.html')));
app.listen(port,()=>console.log(`PrintLink running at http://localhost:${port}`));
